FROM node:9
MAINTAINER Nathan Quarles <nateq314@gmail.com>
RUN apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg && \
	echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
	apt-get update && apt-get install -y \
	yarn && \
	mkdir -p /app
COPY frontend /app
WORKDIR /app
RUN yarn install

EXPOSE 4000

